#!/bin/sh

# Ported from dots/.config/bspwm/bspwmrc for the current Wayland outputs:
# DP-1/DP-2 external, 2560x1440@165, scale 1, position 0,0.
# eDP-1 internal, 2560x1600@240, scale 1.25.

run_if() {
	command -v "$1" >/dev/null 2>&1 && "$@" &
}

output_exists() {
	doorsctl output list | jq -e --arg name "$1" '.[] | select(.name == $name)' >/dev/null
}

configure_outputs() {
	desktops="1 2 3 4 5 6 7 8 9 10"
	external=

	if output_exists DP-1; then
		external=DP-1
	elif output_exists DP-2; then
		external=DP-2
	fi

	doorsctl output eDP-1 enable
	doorsctl output eDP-1 mode 2560x1600@240
	doorsctl output eDP-1 scale 1.25

	if [ -n "$external" ]; then
		doorsctl output "$external" enable
		doorsctl output "$external" mode 2560x1440@165
		doorsctl output "$external" position 0 0
		doorsctl output "$external" scale 1
		doorsctl output eDP-1 position 2560 0

		# Keep Super+0 useful. The bspwmrc created 1-9, but sxhkd also bound desktop 10.
		doorsctl output "$external" -d $desktops
		doorsctl output eDP-1 -d $desktops
		doorsctl output "$external" focus
	else
		doorsctl output eDP-1 position 0 0
		doorsctl output eDP-1 -d $desktops
		doorsctl output eDP-1 focus
	fi

	doorsctl desktop 1
	doorsctl desktop --layout master_stack
}


# Re-run once after startup so a slightly late DP output still gets the external layout.
configure_outputs
(sleep 1; configure_outputs) &

# bspwm visual/tiling settings.
doorsctl config top_padding 22
doorsctl config right_padding 0
doorsctl config bottom_padding 0
doorsctl config left_padding 0
doorsctl config normal_border_gradient 282a36 44475a 90deg
doorsctl config active_border_gradient 8be9fd bd93f9 90deg
doorsctl config focused_border_gradient de83c6 ff79c6 90deg
doorsctl config normal_border_gradient2 clear
doorsctl config active_border_gradient2 clear
doorsctl config focused_border_gradient2 clear
doorsctl config normal_border_gradient_lerp 0.0
doorsctl config active_border_gradient_lerp 0.0
doorsctl config focused_border_gradient_lerp 0.0
doorsctl config border_width 1
doorsctl config window_gap 10
doorsctl config click_to_focus true
doorsctl config split_ratio 0.52
doorsctl config borderless_monocle true
doorsctl config gapless_monocle true
doorsctl config single_monocle true
doorsctl config decoration_mode tabs
doorsctl config enable_animations true

# Pointer defaults.
doorsctl input type:touchpad tap true
doorsctl input type:touchpad natural_scroll true

doorsctl env set XCURSOR_SIZE 24
doorsctl env set MOZ_ENABLE_WAYLAND 1
doorsctl env set XDG_CURRENT_DESKTOP doors
doorsctl env set QT_QPA_PLATFORMTHEME qt6ct


run_if mako
run_if nm-applet
run_if waybar -c "$HOME/.config/waybar/config.jsonc" -s "$HOME/.config/waybar/style.css"
run_if waypaper --restore
if ! pidof pipewire >/dev/null 2>&1; then
	run_if gentoo-pipewire-launcher restart
fi

if [ -x /usr/libexec/xfce-polkit ]; then
	/usr/libexec/xfce-polkit &
fi

doorsctl config blur_enabled true
doorsctl config mica_enabled true
doorsctl config blur_algorithm box
doorsctl config blur_radius 15

doorsctl rule -a com.dec05eba.gpu_screen_recorder state=floating
doorsctl rule -a dev.zed.Zed blur=on mica=on
doorsctl rule -a zen blur=on
doorsctl rule -a discord desktop=8

doorsctl rule -a com.mitchellh.ghostty blur=on 

doorsctl rule -a Alacritty blur=on
# doorsctl rule -a com.mitchellh.ghostty blur=on

systemctl --user set-environment \
    XDG_CURRENT_DESKTOP=doors \

systemctl --user import-environment \
    DISPLAY \
    WAYLAND_DISPLAY \
    XDG_CURRENT_DESKTOP \
    QT_QPA_PLATFORMTHEME

dbus-update-activation-environment --systemd \
    DISPLAY \
    WAYLAND_DISPLAY \
    XDG_CURRENT_DESKTOP=doors \


doorsctl env set QT_QPA_PLATFORMTHEME qt6ct
doorsctl env set QT_QPA_PLATFORM wayland

systemctl --user start doors-session.service
xwaylandvideobridge &

doorsctl desktop --layout master_stack
