[settings]
set_wallpaper = true
gtk = true
active = 0
light_theme = false
editor = urxvt -e vim
execute_cmd = true
command = /home/nat/.config/waybar/scripts/wpg-sync-theme.sh sync
backend = wal
alpha = 100
smart_sort = true
auto_adjust = false
reload = true
terminal = true
keywords = default

[keywords]

